### ISSUE TITLE
Navigation-Bar

### ISSUE THREAD

**Issue by thomasweigert91** [thomasweigert91/capstone#1]
### Value Proposition

As a user, i want to be able to navigate quickly and specifically through the app. For this I need a navigation bar. It should lead me to the core features of the app.

### Description

![image](https://user-images.githubusercontent.com/114309234/204283162-7e63c9cf-a685-40fc-8bc7-14f2521393b6.png)

### Acceptance Criteria

- [ ] the navigation bar is located at the bottom of the screen
- [ ] it contains several icons that illustrate the task area of the respective page
- [ ] by clicking on the respective symbol you will get to the corresponding page

### Tasks

(for developers team)

- [ ] create navbar component
- [ ] stick it to the bottom 
- [ ] insert three icons to navigate to the core features
- [ ] implement routing option
- [ ] add color to the button, if page is active

### Sizing/Complexity

**M**
