### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by thomasweigert91** [thomasweigert91/capstone#2]
### Value Proposition

As a user I want to see the name of the current page in the header. Additional options for the respective page are represented by icons in the header. On pages where there is no navigation bar, I want to be able to navigate to the home page via an arrow in the header.

### Description

![image](https://user-images.githubusercontent.com/114309234/204284955-4dd1064a-8d3d-48b2-8dcd-bc968b92fb50.png)
![image](https://user-images.githubusercontent.com/114309234/204285015-c5a9be0b-1e46-4df2-90e9-81b484603e91.png)
![image](https://user-images.githubusercontent.com/114309234/204285071-a24ed38e-b010-4307-88ce-b0a7f8f6c013.png)

### Acceptance Criteria

- [ ] by default the header shows the name of the respective page
- [ ] Pages that do not have a navigation bar have an icon in the header to return to the home page
- [ ] in training mode, a stopwatch is also displayed to call up a corresponding feature

### Tasks

(for developers team)

- [ ] create header component
- [ ] adjust content for every page
- [ ] add possibility to navigate back to the homepage on several pages

### Sizing/Complexity

** M **
